### PR TITLE
Remove MacOS binary from root.

### LINKED ISSUE #415: Remove MacOS binary from top-level directory
Remove https://github.com/Electrostatics/pdb2pqr/blob/2e8b98f8b812608757f4b4a5729359d6ade9cfd9/pdb2pka from top-level directory.

I'm not sure why it is here...

### PR DESCRIPTION
**Pull request by sobolevnrm**
Fixes #415

### CODE REVIEW

**Comment by sobolevnrm** [comment]
@kiyoon can you review this when you have time?

**Comment by kiyoon** [comment]
@sobolevnrm I actually don't understand what pdb2pka does. Maybe it was included for testing but since the CI test passes, it should be fine? Is it ever being used? I don't see it in the dependencies

**Comment by sobolevnrm** [comment]
No, I think it was dropped there accidentally a long time ago.  We've removed all of the dependencies and don't use it any longer.

**Review by kiyoon — APPROVED** [review]

**Review by kiyoon — APPROVED** [review]

**Comment by kiyoon** [comment]
I don't think my review matters because I don't have the write access

**Comment by sobolevnrm** [comment]
Thanks!

**Pull request merged**
