### PR TITLE
Enable CI

### LINKED ISSUE #68: Nathan needs to fix the overly comprehensive tests
`lengthy_basic_test.py` is going to break our CI setup.

### PR DESCRIPTION
**Pull request by sobolevnrm**
This is an attempt to jumpstart CI and coverage tests for PDB2PQR.  This will probably require multiple PRs and tests -- apologies in advance for trying everyone's patience.

Fixes #68

### CODE REVIEW

**Comment by sobolevnrm** [comment]
My commit has lots of problems.  I think we need to switch to `flake8` for PDB2PQR de-linting.

**Comment by sobolevnrm** [comment]
> This is a big change. I will review it closer tomorrow morning.

The original change was small (just removing one test to enable timely CI).  But the tests failed because of flake8 errors so I started de-linting based on that to clean things up.  Most of what you see now are delinting-related changes.

**Comment by intendo** [comment]
The `pdb2pqr/hydrogens/__init__.py` is trying to do a `getattr` on a class named structures. Shouldn't that be `getattr(self, type_)` or a specific class in the structures.py file?

```
./pdb2pqr/hydrogens/__init__.py:321:33: F821 undefined name 'structures'
./pdb2pqr/hydrogens/__init__.py:354:33: F821 undefined name 'structures'
```

If this is fixed, I think most of the checks will pass.

**Comment by sobolevnrm** [comment]
Thanks; I’ll try to work on this tonight.

**Comment by sobolevnrm** [comment]
This was originally intended to be a PR to make CI work for PDB2PQR so we could evaluate test coverage of the code and identify parts of the code that weren't used....  and then @sobolevnrm went down a documentation and de-linting rabbit hole.  He recovered partway through his wandering through the flake8 wilderness (having avoided the [Sphinx](https://www.sphinx-doc.org/en/master/contents.html)) but the result was this strange and bloated PR.  The need for additional de-linting and Sphinx documentation are specified in #75 and #76, respectively.

**Pull request merged**
