### PR TITLE
Version 3.6.2 release candidate

### LINKED ISSUE #377: Release new version
- [ ] Fix https://github.com/jensengroup/propka/issues/168 first.
- [x] Fix #378

### PR DESCRIPTION
**Pull request by sobolevnrm**
Fixes #377

### CODE REVIEW

**Comment by sobolevnrm** [comment]
Preview version of updated docs at https://pdb2pqr.readthedocs.io/en/nathan-378/releases.html.

**Comment by sobolevnrm** [comment]
@orbeckst or @speleo3 can you review this quickly?  Thanks.

**Review by orbeckst — APPROVED** [review]
LGTM

**Comment by sobolevnrm** [comment]
Thanks!

**Pull request merged**
