### PR TITLE
Mark/logging caching

### LINKED ISSUE #66: Print logging for pdb2pqr output files
Output pdb2pqr to log and data files.

### PR DESCRIPTION
**Pull request by bigdawgmj**
close #66

### CODE REVIEW

**Comment by bigdawgmj** [comment]
Please check the cif.py I had to bring a couple empty array assignments out of if statement in order to get it to run properly.  Please let me know if you need me to change that.

**Comment by intendo** [comment]
@sobolevnrm should we be checking generated data files into the repository?

**Comment by sobolevnrm** [comment]
> @sobolevnrm should we be checking generated data files into the repository?

I would only expect to see generated files checked in for regression testing.  I'm confused by the changes to the `tests/data/1a1p*` file -- what's going on there?

**Comment by intendo** [comment]
@sobolevnrm It looks like there is an old convention in the `tests/data/*.pqr` files where they embedded command line options in the output. Maybe they were trying to do regression testing with those parameters. I say we commit @bigdawgmj's changes and then create an issue to deal with test data and clean it up then.

**Comment by sobolevnrm** [comment]
> @sobolevnrm should we be checking generated data files into the repository?

I'm still confused.  What generated files are you referring to?

**Comment by intendo** [comment]
@sobolevnrm The `tests/logging_test.py` test reads in `tests/data/1FAS.pdb` and generates `tests/data/1FAS_pdb.pqr`. Likewise, it reads in `1A1P.pdb` and generates `tests/data/A1P_assign-only_whitespace_ff=AMBER.pqr`. So the generated files from the `tests/logging_test.py` are:
`tests/data/1A1P.pqr` 
`tests/data/1A1P_assign-only_whitespace_ff=AMBER.pqr`

**Comment by sobolevnrm** [comment]
> @sobolevnrm The `tests/logging_test.py` test reads in `tests/data/1FAS.pdb` and generates `tests/data/1FAS_pdb.pqr`. Likewise, it reads in `1A1P.pdb` and generates `tests/data/A1P_assign-only_whitespace_ff=AMBER.pqr`. So the generated files from the `tests/logging_test.py` are:
> `tests/data/1A1P.pqr`
> `tests/data/1A1P_assign-only_whitespace_ff=AMBER.pqr`

Sorry but that doesn't make any sense to me.  The other tests in that directory use `tmp_dir` for generated files.  I'll need to review the code more carefully.

**Comment by bigdawgmj** [comment]
I see how the other test are working, I will fix to match the temporary directory instead and will avoid changing those at all. Thanks and will let you know when it's done

**Comment by bigdawgmj** [comment]
Alright, the logging tests now write and test against the temp directory.  Added the original file back in from the master branch for the 1A1P* file.  Regression tests are passing again as well as the logging tests.

**Comment by sobolevnrm** [comment]
Thanks.  I'll check it out after I push the CI fix in the other branch.

**Pull request merged**
