### PR TITLE
fix: shadowed module recovered `pdb2pqr.main`

### PR DESCRIPTION
**Pull request by kiyoon**
It was impossible to import `import pdb2pqr.main` or use any of the functions in the module because it was shadowed by the name in `pdb2pqr.__init__.py`'s `main()` function. Importing that module will just import the function and the others weren't available.

This allows users to use pdb2pqr as a module, not necessarily as a CLI. Here's an example:

```python
from pdb2pqr.main import build_main_parser, main_driver

parser = build_main_parser()
args = parser.parse_args(["-h"])  # just like `pdb2pqr -h`
main_driver(args)
```

This is a much cleaner way to integrate pdb2pqr in a python project, rather than having to make a subprocess running.  
The reason is that this allows users to adapt debuggers or see the full traceback of PDB2PQR!

In addition, I'm willing to make a simple wrapper of a PDB2PQR like `from pdb2pqr import run_pdb2pqr`, but I think this can be the next PR separate from this.

### CODE REVIEW

**Review by sobolevnrm — APPROVED** [review]

**Comment by sobolevnrm** [comment]
The build actions were messed up; I've fixed them.  Please merge the current master branch into your branch and resubmit the PR.  Sorry for the hassle and thank you for your help with the code.

**Comment by kiyoon** [comment]
Hi, I've merged this so can you try again? Thank you!

**Comment by sobolevnrm** [comment]
It works -- thanks for submitting this!

**Comment by kiyoon** [comment]
Thanks for a quick review! I think I'd like some further changes if you'd agree as well.

1. run_pdb2pqr helper function. Given a list of strings, run pdb2pqr like it was a CLI. But except setup_logging because users would like to set it up themselves however they'd like.
2. Add types as much as possible
3. Apply ruff format and isort (put the settings in pyproject.toml)

**Comment by sobolevnrm** [comment]
Sure!  Can you file an issue for each and we can discuss implementation?  Thanks!

**Pull request merged**
