### PR TITLE
Update documentation testing and dependencies.

### LINKED ISSUE #371: update docutils please?
At least `0.18.1`, there's an important fix in that version. `sphinx` errors out with docutils `<=0.18`

### PR DESCRIPTION
**Pull request by sobolevnrm**
Fixes #371

### CODE REVIEW

**Comment by kiyoon** [comment]
It's just a suggestion, but if you are willing to make some changes, I think mkdocs (material theme) is widely used and much more intuitive than Sphinx, using markdown as the main format. Using easier setup also means there will be more contributions. I'm happy to help if you are willing to at least try it out!

**Comment by sobolevnrm** [comment]
> It's just a suggestion, but if you are willing to make some changes, I think mkdocs (material theme) is widely used and much more intuitive than Sphinx, using markdown as the main format. Using easier setup also means there will be more contributions. I'm happy to help if you are willing to at least try it out!

That's an interesting suggestion.  I'll create an issue and we can figure it out there.  Thanks!

**Comment by sobolevnrm** [comment]
@kiyoon How do I catch the `ruff` errors in the build above before committing?  I ran

`ruff format --check --diff --config pyproject.toml .`

but it didn't catch the ones flagged in the build/test.

**Comment by sobolevnrm** [comment]
> @kiyoon How do I catch the `ruff` errors in the build above before committing? I ran
> 
> `ruff format --check --diff --config pyproject.toml .`
> 
> but it didn't catch the ones flagged in the build/test.

Never mind:  `ruff check --select I --diff --config pyproject.toml .` works.

**Comment by kiyoon** [comment]
I didn't fix all of the lint errors yet, and they still need to be addressed.

In fact, there are some errors I don't like as much, and it really depends on the project so we should discuss which to ignore further.

The `--select I` means you selected isort errors, which you must apply before publishing because it's easy to.

The `--config pyproject.toml` is redundant as it will by default select from there.

If you set `--config ruff_essential.toml` it grabs all the syntax errors that must pass.

**Comment by kiyoon** [comment]
Fixing isort error is something like `ruff check --select I --fix .`

**Comment by sobolevnrm** [comment]
Yes, some of the errors seem overly pedantic and we should discuss. Thanks!

**Review by kiyoon — APPROVED** [review]

**Pull request merged**
